# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CCmadeM <- function(X_train, X_test, y_train, chunk, cc_num) {
    .Call(`_CCFM_CCmadeM`, X_train, X_test, y_train, chunk, cc_num)
}

CCmadeBM <- function(bX_train, bX_test, by_train, chunk, cc_num) {
    .Call(`_CCFM_CCmadeBM`, bX_train, bX_test, by_train, chunk, cc_num)
}

